name: Trigger auto deployment for container-app-emxayctxgjsos

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-emxayctxgjsos-AutoDeployTrigger-79cb357c-a3f3-4f9e-b5f2-8ca8edb340d6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPEMXAYCTXGJSOS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPEMXAYCTXGJSOS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPEMXAYCTXGJSOS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPEMXAYCTXGJSOS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPEMXAYCTXGJSOS_REGISTRY_PASSWORD }}
          containerAppName: container-app-emxayctxgjsos
          resourceGroup: ragappspacesandboxrepo8d3c
          imageToBuild: default/container-app-emxayctxgjsos:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


